# Generated by Django 3.0.6 on 2021-01-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210115_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastMessageSeen',
        ),
    ]
