# Generated by Django 3.0.6 on 2020-11-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_messeages_preferences'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messeages',
            new_name='Messages',
        ),
    ]
